### PR TITLE
added autocorrect and test cases for it.

### PR DESCRIPTION
**Pull request by akshaynagpal**
Autocorrect still not giving us the results we need. Check in testcases file.

Also, I am not able to run the app even after doing 

```
$ pip install -r requirements.txt
Requirement already satisfied: Flask_Bootstrap==3.3.7.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Jinja2==2.8 in c:\python27\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: MarkupSafe==0.23 in c:\python27\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: Werkzeug==0.11.10 in c:\python27\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: click==6.6 in c:\python27\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: gunicorn==19.6.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: itsdangerous==0.24 in c:\python27\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: wsgiref==0.1.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: watson-developer-cloud==0.20.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: fuzzywuzzy==0.14.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: numpy==1.11.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 11))
Requirement already satisfied: requests==2.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 12))
Requirement already satisfied: tqdm==4.8.4 in c:\python27\lib\site-packages (from -r requirements.txt (line 13))
Requirement already satisfied: Flask==0.11.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 14))
Requirement already satisfied: nltk==3.2.1 in c:\python27\lib\site-packages (from -r requirements.txt (line 15))
Requirement already satisfied: psycopg2==2.6.2 in c:\python27\lib\site-packages (from -r requirements.txt (line 16))
Requirement already satisfied: python_dateutil==2.6.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 17))
Requirement already satisfied: autocorrect==0.3.0 in c:\python27\lib\site-packages (from -r requirements.txt (line 18))
Requirement already satisfied: dominate in c:\python27\lib\site-packages (from Flask_Bootstrap==3.3.7.0->-r requirements.txt (line 1))
Requirement already satisfied: visitor in c:\python27\lib\site-packages (from Flask_Bootstrap==3.3.7.0->-r requirements.txt (line 1))
Requirement already satisfied: pysolr<4.0,>=3.3 in c:\python27\lib\site-packages (from watson-developer-cloud==0.20.0->-r requirements.txt (line 9))
Requirement already satisfied: six>=1.5 in c:\python27\lib\site-packages (from python_dateutil==2.6.0->-r requirements.txt (line 17))

```

Then I did:
```
$ python app.py
C:\Python27\lib\site-packages\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
 * Restarting with stat
C:\Python27\lib\site-packages\fuzzywuzzy\fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
 * Debugger is active!
 * Debugger pin code: 186-802-405
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

```

Now, when I go to http://127.0.0.1:5000/feedback
I typed: "deadline for phd admissions?"
Next page I see the error:
```
ImportError: No module named copy_reg

File "C:\Python27\lib\site-packages\flask\app.py", line 2000, in __call__
return self.wsgi_app(environ, start_response)
File "C:\Python27\lib\site-packages\flask\app.py", line 1991, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "C:\Python27\lib\site-packages\flask\app.py", line 1567, in handle_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1641, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Python27\lib\site-packages\flask\app.py", line 1544, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Python27\lib\site-packages\flask\app.py", line 1639, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Python27\lib\site-packages\flask\app.py", line 1625, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "C:\Users\akshay\Documents\GitHub\graduate-affairs-bot\app.py", line 56, in displayQuestionForm
result = engine.process_message(1, question)
File "C:\Users\akshay\Documents\GitHub\graduate-affairs-bot\core\engine.py", line 72, in process_message
basic_response = self.basic_responder.check_and_respond(message)
File "C:\Users\akshay\Documents\GitHub\graduate-affairs-bot\core\basic_responder.py", line 58, in check_and_respond
if self.requires_basic_response(message):
File "C:\Users\akshay\Documents\GitHub\graduate-affairs-bot\core\basic_responder.py", line 38, in requires_basic_response
tokens = nlp.tokenize_text(message)
File "C:\Users\akshay\Documents\GitHub\graduate-affairs-bot\core\nlp.py", line 51, in tokenize_text
return nltk.word_tokenize(text)
File "C:\Python27\lib\site-packages\nltk\tokenize\__init__.py", line 106, in word_tokenize
Open an interactive python shell in this framereturn [token for sent in sent_tokenize(text, language)
File "C:\Python27\lib\site-packages\nltk\tokenize\__init__.py", line 90, in sent_tokenize
tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
File "C:\Python27\lib\site-packages\nltk\data.py", line 806, in load
resource_val = pickle.load(opened_resource)
ImportError: No module named copy_reg
```

Went to StackOverflow to check:
http://stackoverflow.com/questions/556269/importerror-no-module-named-copy-reg-pickle

Hence I am not able to fix global variables issue.

### CODE REVIEW

**Comment by rohankshir** [comment]
you're definitely using python 2.7?

**Comment by rohankshir** [comment]
for now you can replace the call to nltk word_tokenize (locally) with a call to split so you can fix the global variables thing

**Comment by akshaynagpal** [comment]
global variables removed. @rohankshir You can merge PR now.

**Comment by rohankshir** [comment]
thanks!

**Pull request merged**
